FROM public.ecr.aws/docker/library/node:20-alpine

ENV PNPM_HOME="/pnpm" \
    PATH="${PNPM_HOME}:${PATH}"

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./

RUN pnpm install --ignore-scripts

COPY . .

EXPOSE 3000

CMD ["sh", "-c", "pnpm run build && pnpm run preview"]