FROM public.ecr.aws/docker/library/node:20-alpine

ENV PNPM_HOME="/pnpm" \
    PATH="${PNPM_HOME}:${PATH}"

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./

RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 3000

CMD ["pnpm", "run", "dev", "--host", "0.0.0.0", "--port", "3000"]