"""
Curated ingredient catalog seed (RB-ING-01).

Each entry: (slug, name, category, default_unit, aliases).
Categories: proteina, verdura, fruta, lacteo, grano, condimento, grasa, otro.
Units: g, kg, ml, l, unidad, cucharada, cucharadita, taza, pizca.
"""

INGREDIENTS: list[tuple[str, str, str, str, list[str]]] = [
    # ---------------------------------------------------------------- proteina
    ("pollo", "Pollo", "proteina", "g", ["pechuga", "suprema"]),
    ("pechuga-de-pollo", "Pechuga de pollo", "proteina", "g", []),
    ("muslo-de-pollo", "Muslo de pollo", "proteina", "g", []),
    ("pata-de-pollo", "Pata de pollo", "proteina", "g", []),
    ("alitas-de-pollo", "Alitas de pollo", "proteina", "g", []),
    ("carne-vacuna", "Carne vacuna", "proteina", "g", ["res", "bife"]),
    ("carne-picada", "Carne picada", "proteina", "g", ["picada"]),
    ("bife-de-chorizo", "Bife de chorizo", "proteina", "g", []),
    ("asado", "Asado", "proteina", "g", ["costilla"]),
    ("lomo", "Lomo", "proteina", "g", []),
    ("matambre", "Matambre", "proteina", "g", []),
    ("milanesa", "Milanesa", "proteina", "g", []),
    ("osobuco", "Osobuco", "proteina", "g", []),
    ("cerdo", "Carne de cerdo", "proteina", "g", ["chancho"]),
    ("bondiola", "Bondiola", "proteina", "g", []),
    ("panceta", "Panceta", "proteina", "g", ["tocino"]),
    ("chorizo", "Chorizo", "proteina", "unidad", []),
    ("chorizo-colorado", "Chorizo colorado", "proteina", "unidad", []),
    ("morcilla", "Morcilla", "proteina", "unidad", []),
    ("salchicha", "Salchicha", "proteina", "unidad", []),
    ("salchicha-parrillera", "Salchicha parrillera", "proteina", "unidad", []),
    ("jamon-cocido", "Jamón cocido", "proteina", "g", []),
    ("jamon-crudo", "Jamón crudo", "proteina", "g", ["serrano"]),
    ("salame", "Salame", "proteina", "g", []),
    ("mortadela", "Mortadela", "proteina", "g", []),
    ("cordero", "Cordero", "proteina", "g", ["ternasco"]),
    ("conejo", "Conejo", "proteina", "g", []),
    ("pato", "Pato", "proteina", "g", []),
    ("pavo", "Pavo", "proteina", "g", []),
    ("pescado", "Pescado", "proteina", "g", []),
    ("merluza", "Merluza", "proteina", "g", []),
    ("salmon", "Salmón", "proteina", "g", []),
    ("atun", "Atún", "proteina", "g", []),
    ("atun-en-lata", "Atún en lata", "proteina", "g", ["atún al natural"]),
    ("tilapia", "Tilapia", "proteina", "g", []),
    ("trucha", "Trucha", "proteina", "g", []),
    ("corvina", "Corvina", "proteina", "g", []),
    ("bacalao", "Bacalao", "proteina", "g", []),
    ("sardinas", "Sardinas", "proteina", "g", []),
    ("camarones", "Camarones", "proteina", "g", []),
    ("langostinos", "Langostinos", "proteina", "g", []),
    ("mejillones", "Mejillones", "proteina", "g", []),
    ("calamar", "Calamar", "proteina", "g", []),
    ("pulpo", "Pulpo", "proteina", "g", []),
    ("huevo", "Huevo", "proteina", "unidad", ["huevos"]),
    ("clara-de-huevo", "Clara de huevo", "proteina", "unidad", []),
    ("yema", "Yema", "proteina", "unidad", []),
    ("tofu", "Tofu", "proteina", "g", []),
    ("tempeh", "Tempeh", "proteina", "g", []),
    ("seitan", "Seitán", "proteina", "g", []),
    ("lentejas", "Lentejas", "proteina", "g", []),
    ("garbanzos", "Garbanzos", "proteina", "g", []),
    ("porotos", "Porotos", "proteina", "g", ["frijoles"]),
    ("porotos-negros", "Porotos negros", "proteina", "g", []),
    ("porotos-blancos", "Porotos blancos", "proteina", "g", []),
    ("arvejas", "Arvejas", "proteina", "g", ["guisantes"]),
    ("habas", "Habas", "proteina", "g", []),
    ("soja-texturizada", "Soja texturizada", "proteina", "g", []),
    # ----------------------------------------------------------------- verdura
    ("tomate", "Tomate", "verdura", "g", ["tomate pera", "cherry"]),
    ("tomate-perita", "Tomate perita", "verdura", "g", []),
    ("tomate-cherry", "Tomate cherry", "verdura", "g", []),
    ("cebolla", "Cebolla", "verdura", "unidad", []),
    ("cebolla-morada", "Cebolla morada", "verdura", "unidad", []),
    ("cebolla-de-verdeo", "Cebolla de verdeo", "verdura", "unidad", ["cebollita"]),
    ("ajo", "Ajo", "verdura", "unidad", ["diente de ajo"]),
    ("puerro", "Puerro", "verdura", "unidad", []),
    ("zanahoria", "Zanahoria", "verdura", "g", []),
    ("papa", "Papa", "verdura", "g", ["patata"]),
    ("batata", "Batata", "verdura", "g", ["boniato", "camote"]),
    ("zapallo", "Zapallo", "verdura", "g", ["calabaza", "anco"]),
    ("zucchini", "Zucchini", "verdura", "g", ["calabacín"]),
    ("berenjena", "Berenjena", "verdura", "unidad", []),
    ("morron-rojo", "Morrón rojo", "verdura", "unidad", ["pimiento"]),
    ("morron-verde", "Morrón verde", "verdura", "unidad", []),
    ("morron-amarillo", "Morrón amarillo", "verdura", "unidad", []),
    ("apio", "Apio", "verdura", "g", []),
    ("lechuga", "Lechuga", "verdura", "g", []),
    ("lechuga-romana", "Lechuga romana", "verdura", "g", []),
    ("rucula", "Rúcula", "verdura", "g", []),
    ("espinaca", "Espinaca", "verdura", "g", []),
    ("acelga", "Acelga", "verdura", "g", []),
    ("repollo", "Repollo", "verdura", "g", ["col"]),
    ("repollito-de-bruselas", "Repollito de Bruselas", "verdura", "g", []),
    ("coliflor", "Coliflor", "verdura", "g", []),
    ("brocoli", "Brócoli", "verdura", "g", []),
    ("rabano", "Rábano", "verdura", "g", []),
    ("remolacha", "Remolacha", "verdura", "g", ["betabel"]),
    ("pepino", "Pepino", "verdura", "unidad", []),
    ("chaucha", "Chaucha", "verdura", "g", ["ejotes", "vainitas"]),
    ("choclo", "Choclo", "verdura", "g", ["maíz tierno"]),
    ("champiñon", "Champiñón", "verdura", "g", ["hongos"]),
    ("portobello", "Portobello", "verdura", "g", []),
    ("berro", "Berro", "verdura", "g", []),
    ("escarola", "Escarola", "verdura", "g", []),
    ("endivia", "Endivia", "verdura", "g", []),
    ("alcachofa", "Alcachofa", "verdura", "unidad", []),
    ("esparrago", "Espárrago", "verdura", "g", []),
    ("alcaucil", "Alcaucil", "verdura", "unidad", []),
    ("jengibre", "Jengibre", "verdura", "g", []),
    ("ciboulette", "Ciboulette", "verdura", "g", ["cibollita"]),
    ("perejil", "Perejil", "verdura", "g", []),
    ("cilantro", "Cilantro", "verdura", "g", []),
    ("albahaca", "Albahaca", "verdura", "g", []),
    ("menta", "Menta", "verdura", "g", []),
    ("romero", "Romero", "verdura", "g", []),
    ("tomillo", "Tomillo", "verdura", "g", []),
    ("oregano", "Orégano", "verdura", "g", []),
    ("laurel", "Laurel", "verdura", "unidad", []),
    ("salvia", "Salvia", "verdura", "g", []),
    ("hinojo", "Hinojo", "verdura", "g", []),
    ("manzanilla", "Manzanilla", "verdura", "g", []),
    ("jalapeno", "Jalapeño", "verdura", "unidad", []),
    ("aji", "Ají", "verdura", "unidad", ["chile"]),
    ("aji-picante", "Ají picante", "verdura", "g", []),
    ("nabo", "Nabo", "verdura", "g", []),
    ("chirivia", "Chirivía", "verdura", "g", []),
    ("mandioca", "Mandioca", "verdura", "g", ["yuca"]),
    ("chayote", "Chayote", "verdura", "unidad", []),
    ("vaina", "Vaina", "verdura", "g", []),
    ("germen-de-soja", "Germen de soja", "verdura", "g", []),
    ("alga-nori", "Alga nori", "verdura", "g", []),
    ("alga-wakame", "Alga wakame", "verdura", "g", []),
    ("hongo-shitake", "Hongo shiitake", "verdura", "g", []),
    ("calabacin", "Calabacín", "verdura", "unidad", []),
    ("calabaza-criolla", "Calabaza criolla", "verdura", "g", []),
    ("brotes-verdes", "Brotes verdes", "verdura", "g", []),
    ("pimiento-rojo", "Pimiento rojo", "verdura", "unidad", []),
    ("pimiento-verde", "Pimiento verde", "verdura", "unidad", []),
    ("palmitos", "Palmitos", "verdura", "g", []),
    # ------------------------------------------------------------------- fruta
    ("manzana", "Manzana", "fruta", "unidad", []),
    ("manzana-verde", "Manzana verde", "fruta", "unidad", []),
    ("pera", "Pera", "fruta", "unidad", []),
    ("banana", "Banana", "fruta", "unidad", ["plátano"]),
    ("naranja", "Naranja", "fruta", "unidad", []),
    ("mandarina", "Mandarina", "fruta", "unidad", []),
    ("limon", "Limón", "fruta", "unidad", []),
    ("lima", "Lima", "fruta", "unidad", []),
    ("pomelo", "Pomelo", "fruta", "unidad", ["toronja"]),
    ("frutilla", "Frutilla", "fruta", "g", ["fresa"]),
    ("arandano", "Arándano", "fruta", "g", []),
    ("frambuesa", "Frambuesa", "fruta", "g", []),
    ("mora", "Mora", "fruta", "g", ["zarzamora"]),
    ("uva", "Uva", "fruta", "g", []),
    ("durazno", "Durazno", "fruta", "unidad", ["melocotón"]),
    ("damasco", "Damasco", "fruta", "unidad", ["albaricoque"]),
    ("ciruela", "Ciruela", "fruta", "unidad", []),
    ("cereza", "Cereza", "fruta", "g", []),
    ("kiwi", "Kiwi", "fruta", "unidad", []),
    ("mango", "Mango", "fruta", "unidad", []),
    ("papaya", "Papaya", "fruta", "unidad", []),
    ("pina", "Piña", "fruta", "g", ["anana", "ananas"]),
    ("sandia", "Sandía", "fruta", "g", []),
    ("melon", "Melón", "fruta", "unidad", []),
    ("palta", "Palta", "fruta", "unidad", ["aguacate"]),
    ("coco", "Coco", "fruta", "unidad", []),
    ("granada", "Granada", "fruta", "unidad", []),
    ("higo", "Higo", "fruta", "unidad", []),
    ("datil", "Dátil", "fruta", "g", []),
    ("membrillo", "Membrillo", "fruta", "unidad", []),
    ("caqui", "Caqui", "fruta", "unidad", []),
    ("guayaba", "Guayaba", "fruta", "unidad", []),
    ("maracuya", "Maracuyá", "fruta", "unidad", ["fruta de la pasión"]),
    ("frutilla-del-bosque", "Frutilla del bosque", "fruta", "g", []),
    ("mandarina-clementina", "Clementina", "fruta", "unidad", []),
    ("uva-pasa", "Uva pasa", "fruta", "g", ["pasas"]),
    ("ciruela-pasa", "Ciruela pasa", "fruta", "g", []),
    ("orejon", "Orejón", "fruta", "g", ["durazno deshidratado"]),
    ("cereza-marron", "Cereza marrón", "fruta", "g", []),
    ("banana-de-morada", "Banana de morada", "fruta", "unidad", []),
    # ------------------------------------------------------------------ lacteo
    ("leche", "Leche", "lacteo", "ml", []),
    ("leche-entera", "Leche entera", "lacteo", "ml", []),
    ("leche-descremada", "Leche descremada", "lacteo", "ml", []),
    ("leche-vegetal", "Leche vegetal", "lacteo", "ml", ["bebida vegetal"]),
    ("crema", "Crema", "lacteo", "ml", ["nata"]),
    ("crema-para-batir", "Crema para batir", "lacteo", "ml", []),
    ("crema-agria", "Crema agria", "lacteo", "ml", ["sour cream"]),
    ("yogur", "Yogur", "lacteo", "g", []),
    ("yogur-griego", "Yogur griego", "lacteo", "g", []),
    ("queso", "Queso", "lacteo", "g", []),
    ("queso-cremoso", "Queso cremoso", "lacteo", "g", []),
    ("queso-mozzarella", "Queso mozzarella", "lacteo", "g", ["muzza"]),
    ("queso-parmesano", "Queso parmesano", "lacteo", "g", []),
    ("queso-rallado", "Queso rallado", "lacteo", "g", []),
    ("queso-cheddar", "Queso cheddar", "lacteo", "g", []),
    ("queso-azul", "Queso azul", "lacteo", "g", ["roquefort"]),
    ("queso-de-cabra", "Queso de cabra", "lacteo", "g", []),
    ("queso-port-salut", "Queso port salut", "lacteo", "g", []),
    ("queso-mascarpone", "Queso mascarpone", "lacteo", "g", []),
    ("queso-ricota", "Ricota", "lacteo", "g", ["requesón"]),
    ("manteca", "Manteca", "lacteo", "g", ["mantequilla"]),
    ("margarina", "Margarina", "lacteo", "g", []),
    ("dulce-de-leche", "Dulce de leche", "lacteo", "g", []),
    ("crema-de-leche", "Crema de leche", "lacteo", "ml", []),
    ("leche-condensada", "Leche condensada", "lacteo", "g", []),
    ("leche-en-polvo", "Leche en polvo", "lacteo", "g", []),
    ("kefir", "Kéfir", "lacteo", "ml", []),
    ("suero-de-leche", "Suero de leche", "lacteo", "ml", ["buttermilk"]),
    ("queso-feta", "Queso feta", "lacteo", "g", []),
    ("provoleta", "Provoleta", "lacteo", "g", []),
    # ------------------------------------------------------------------- grano
    ("harina", "Harina", "grano", "g", ["harina 000", "harina 0000"]),
    ("harina-integral", "Harina integral", "grano", "g", []),
    ("harina-de-almendras", "Harina de almendras", "grano", "g", []),
    ("arroz", "Arroz", "grano", "g", []),
    ("arroz-integral", "Arroz integral", "grano", "g", []),
    ("arroz-yamani", "Arroz yamaní", "grano", "g", []),
    ("fideos", "Fideos", "grano", "g", ["pasta"]),
    ("fideos-secos", "Fideos secos", "grano", "g", []),
    ("tallarines", "Tallarines", "grano", "g", []),
    ("spaghetti", "Spaghetti", "grano", "g", []),
    ("ravioles", "Ravioles", "grano", "g", []),
    ("noquis", "Ñoquis", "grano", "g", []),
    ("pan", "Pan", "grano", "g", []),
    ("pan-rallado", "Pan rallado", "grano", "g", []),
    ("pan-lactal", "Pan lactal", "grano", "g", []),
    ("pan-integral", "Pan integral", "grano", "g", []),
    ("avena", "Avena", "grano", "g", []),
    ("avena-instantanea", "Avena instantánea", "grano", "g", []),
    ("cebada", "Cebada", "grano", "g", []),
    ("centeno", "Centeno", "grano", "g", []),
    ("quinoa", "Quinoa", "grano", "g", []),
    ("cuscus", "Cuscús", "grano", "g", []),
    ("polenta", "Polenta", "grano", "g", []),
    ("semola", "Sémola", "grano", "g", []),
    ("maicena", "Maicena", "grano", "g", ["almidón de maíz"]),
    ("trigo-burgol", "Trigo burgol", "grano", "g", ["bulgur"]),
    ("germen-de-trigo", "Germen de trigo", "grano", "g", []),
    ("salvado", "Salvado", "grano", "g", []),
    ("tapioca", "Tapioca", "grano", "g", []),
    ("levadura", "Levadura", "grano", "g", []),
    ("levadura-en-polvo", "Levadura en polvo", "grano", "g", []),
    ("polvo-de-hornear", "Polvo de hornear", "grano", "cucharadita", ["bicarbonato"]),
    ("bicarbonato-de-sodio", "Bicarbonato de sodio", "grano", "cucharadita", []),
    ("lentejon", "Lentejón", "grano", "g", []),
    ("maiz", "Maíz", "grano", "g", []),
    # -------------------------------------------------------------- condimento
    ("sal", "Sal", "condimento", "cucharadita", []),
    ("sal-marina", "Sal marina", "condimento", "cucharadita", []),
    ("pimienta-negra", "Pimienta negra", "condimento", "cucharadita", []),
    ("pimienta-blanca", "Pimienta blanca", "condimento", "cucharadita", []),
    ("pimenton", "Pimentón", "condimento", "cucharadita", ["paprika"]),
    ("pimenton-dulce", "Pimentón dulce", "condimento", "cucharadita", []),
    ("comino", "Comino", "condimento", "cucharadita", []),
    ("curcuma", "Cúrcuma", "condimento", "cucharadita", []),
    ("curry", "Curry", "condimento", "cucharadita", []),
    ("canela", "Canela", "condimento", "cucharadita", []),
    ("nuez-moscada", "Nuez moscada", "condimento", "pizca", []),
    ("clavo-de-olor", "Clavo de olor", "condimento", "unidad", []),
    ("anís", "Anís", "condimento", "cucharadita", []),
    ("vainilla", "Vainilla", "condimento", "cucharadita", ["esencia de vainilla"]),
    ("azucar", "Azúcar", "condimento", "g", []),
    ("azucar-impalpable", "Azúcar impalpable", "condimento", "g", []),
    ("azucar-rubia", "Azúcar rubia", "condimento", "g", []),
    ("azucar-negra", "Azúcar negra", "condimento", "g", []),
    ("edulcorante", "Edulcorante", "condimento", "pizca", []),
    ("miel", "Miel", "condimento", "g", []),
    ("miel-de-cana", "Miel de caña", "condimento", "g", []),
    ("cacao", "Cacao", "condimento", "g", ["cacao amargo"]),
    ("chocolate", "Chocolate", "condimento", "g", []),
    ("chocolate-amargo", "Chocolate amargo", "condimento", "g", []),
    ("vainillas", "Vainillas", "condimento", "unidad", []),
    ("vinagre", "Vinagre", "condimento", "ml", []),
    ("vinagre-de-manzana", "Vinagre de manzana", "condimento", "ml", []),
    ("vinagre-balsamico", "Vinagre balsámico", "condimento", "ml", []),
    ("salsa-de-soja", "Salsa de soja", "condimento", "ml", ["soya"]),
    ("salsa-inglesa", "Salsa inglesa", "condimento", "ml", ["worcestershire"]),
    ("mostaza", "Mostaza", "condimento", "cucharada", []),
    ("ketchup", "Kétchup", "condimento", "cucharada", []),
    ("mayonesa", "Mayonesa", "condimento", "cucharada", []),
    ("salsa-de-tomate", "Salsa de tomate", "condimento", "g", []),
    ("extracto-de-tomate", "Extracto de tomate", "condimento", "cucharada", []),
    ("caldo", "Caldo", "condimento", "unidad", ["caldo de verduras"]),
    ("caldo-de-pollo", "Caldo de pollo", "condimento", "unidad", []),
    ("caldo-de-carne", "Caldo de carne", "condimento", "unidad", []),
    ("gelatina", "Gelatina", "condimento", "g", []),
    ("esencia-de-almendra", "Esencia de almendra", "condimento", "cucharadita", []),
    ("colorante", "Colorante", "condimento", "pizca", []),
    ("aji-molido", "Ají molido", "condimento", "cucharadita", []),
    ("pimienta-cayena", "Pimienta cayena", "condimento", "pizca", []),
    ("jengibre-en-polvo", "Jengibre en polvo", "condimento", "cucharadita", []),
    ("semillas-de-sesamo", "Semillas de sésamo", "condimento", "cucharada", []),
    ("sesamo", "Sésamo", "condimento", "cucharada", []),
    # ------------------------------------------------------------------- grasa
    ("aceite", "Aceite", "grasa", "ml", []),
    ("aceite-de-oliva", "Aceite de oliva", "grasa", "ml", ["AOVE"]),
    ("aceite-de-girasol", "Aceite de girasol", "grasa", "ml", []),
    ("aceite-de-coco", "Aceite de coco", "grasa", "ml", []),
    ("aceite-de-sesamo", "Aceite de sésamo", "grasa", "ml", []),
    ("aceite-de-maiz", "Aceite de maíz", "grasa", "ml", []),
    ("grasa-de-cerdo", "Grasa de cerdo", "grasa", "g", ["grasa"]),
    ("grasa-vegetal", "Grasa vegetal", "grasa", "g", []),
    ("mantequilla-clarificada", "Mantequilla clarificada", "grasa", "g", ["ghee"]),
    ("manteca-de-cacao", "Manteca de cacao", "grasa", "g", []),
    ("aceitunas", "Aceitunas", "grasa", "g", []),
    ("aceitunas-negras", "Aceitunas negras", "grasa", "g", []),
    ("aceitunas-verdes", "Aceitunas verdes", "grasa", "g", []),
    ("almendras", "Almendras", "grasa", "g", []),
    ("nueces", "Nueces", "grasa", "g", []),
    ("avellanas", "Avellanas", "grasa", "g", []),
    ("castanas-de-caju", "Castañas de cajú", "grasa", "g", ["anacardos"]),
    ("mani", "Maní", "grasa", "g", ["cacahuate"]),
    ("pistachos", "Pistachos", "grasa", "g", []),
    ("semillas-de-girasol", "Semillas de girasol", "grasa", "g", []),
    ("semillas-de-chia", "Semillas de chía", "grasa", "g", []),
    ("semillas-de-lino", "Semillas de lino", "grasa", "g", []),
    # -------------------------------------------------------------------- otro
    ("agua", "Agua", "otro", "ml", []),
    ("agua-con-gas", "Agua con gas", "otro", "ml", []),
    ("vino-blanco", "Vino blanco", "otro", "ml", []),
    ("vino-tinto", "Vino tinto", "otro", "ml", []),
    ("cerveza", "Cerveza", "otro", "ml", []),
    ("ron", "Ron", "otro", "ml", []),
    ("coñac", "Coñac", "otro", "ml", ["brandy"]),
    ("cafe", "Café", "otro", "cucharada", []),
    ("te", "Té", "otro", "unidad", []),
    ("coco-rallado", "Coco rallado", "otro", "g", []),
    ("coco-leche", "Leche de coco", "otro", "ml", []),
    ("pure-de-tomate", "Puré de tomate", "otro", "g", []),
    ("masa-de-tarta", "Masa de tarta", "otro", "unidad", []),
    ("masa-de-empanada", "Masa de empanada", "otro", "unidad", []),
    ("tapa-de-pascualina", "Tapa de pascualina", "otro", "unidad", []),
]
